name: Build iOS Dylib

on:
  push:
    branches: [ main, master ]
  workflow_dispatch:

jobs:
  build:
    runs-on: macos-13

    steps:
    - name: Checkout Code
      uses: actions/checkout@v4

    - name: Setup Theos Environment
      run: |
        bash -c "$(curl -fsSL https://raw.githubusercontent.com/theos/theos/master/bin/install-theos)"
        echo "THEOS=/Users/runner/theos" >> $GITHUB_ENV
        
    - name: Download iOS SDKs
      run: |
        git clone https://github.com/theos/sdks.git /Users/runner/theos/sdks
        
    - name: Compile Source Code
      run: |
        export THEOS=/Users/runner/theos
        make package FINALPACKAGE=1
        
    - name: Upload Output Artifacts
      uses: actions/upload-artifact@v4
      with:
        name: Pool-Mod-Dylib
        path: |
          .theos/obj/*.dylib
          *.deb
