name: Build iOS Dylib

on:
  push:
    branches: [ main, master ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v4

    - name: Install Dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y fakeroot build-essential git perl clang libssl-dev

    - name: Setup Theos Environment
      run: |
        bash -c "$(curl -fsSL https://raw.githubusercontent.com/theos/theos/master/bin/install-theos)"
        echo "THEOS=/home/runner/theos" >> $GITHUB_ENV
        
    - name: Download iOS SDKs
      run: |
        rm -rf /home/runner/theos/sdks
        git clone https://github.com/theos/sdks.git /home/runner/theos/sdks
        
    - name: Compile Source Code
      run: |
        export THEOS=/home/runner/theos
        make package FINALPACKAGE=1
        
    - name: Upload Output Artifacts
      uses: actions/upload-artifact@v4
      with:
        name: Pool-Mod-Package
        path: |
          **/*.dylib
          **/*.deb
